### ISSUE TITLE
Add CPU/Memory HPA orchestration

### ISSUE THREAD

**Issue by stefanprodan** [openfaas-incubator/faas-o6s#13]
Create an HPA object based on these labels:

```
apiVersion: o6s.io/v1alpha1
kind: Function
metadata:
  name: gofast
spec:
  name: gofast
  replicas: 2
  image: alexellis/gofast023
  labels:
    com.openfaas.scale.min: "2"
    com.openfaas.scale.max: "5"
    com.openfaas.scale.cpu: "80"
    com.openfaas.scale.max: "400Mi"
```
